# {{ site. }}

# url: https://innovatiebijdefensie.nl
# baseurl: /CDnE-jekyll-theme-gh-pages/

url: https://github.com/cpcorvers/CDE-new
# baseurl: https://github.com/cpcorvers/CDE-new

# Site settings
title: Innovatie bij Defensie
email: lwc.cde@mindef.nl
description: "Concept Development & Experimentation is een manier waarop de Koninklijke Landmacht invulling geeft aan kort cyclische modernisering in haar optreden en organisatie."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Complex Ede-Driesprong
  - line: Hessenweg 2
  - line: Ede

# Build settings
markdown: kramdown
permalink: pretty
